# -*- coding: utf-8 -*-
"""dl8

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1t07qMRfeH6d47K4UjEDok7Gl204cn7R9
"""

import torch
import torch.nn as nn
import torch.optim as optim
import numpy as np
text = "hello world this is lstm model"
chars = sorted(list(set(text)))
char_to_idx = {ch:i for i,ch in enumerate(chars)}
idx_to_char = {i:ch for ch,i in char_to_idx.items()}
vocab_size = len(chars)
seq_length = 5
hidden_size = 128
embedding_dim = 32
num_layers = 2
learning_rate = 0.01
epochs = 100
def create_dataset(text, seq_length):
    X, Y = [], []
    for i in range(len(text) - seq_length):
        seq = text[i:i+seq_length]
        target = text[i+1:i+seq_length+1]
        X.append([char_to_idx[ch] for ch in seq])
        Y.append([char_to_idx[ch] for ch in target])
    return torch.tensor(X), torch.tensor(Y)
X, Y = create_dataset(text, seq_length)
class CharLSTM(nn.Module):
    def __init__(self):
        super(CharLSTM, self).__init__()
        self.embedding = nn.Embedding(vocab_size, embedding_dim)

        self.lstm = nn.LSTM(
            embedding_dim,
            hidden_size,
            num_layers,
            batch_first=True
        )
        self.fc = nn.Linear(hidden_size, vocab_size)
    def forward(self, x, hidden):
        x = self.embedding(x)
        out, hidden = self.lstm(x, hidden)
        out = self.fc(out)
        return out, hidden

    def init_hidden(self, batch_size):
        return (
            torch.zeros(num_layers, batch_size, hidden_size),
            torch.zeros(num_layers, batch_size, hidden_size)
        )
model = CharLSTM()
criterion = nn.CrossEntropyLoss()
optimizer = optim.Adam(model.parameters(), lr=learning_rate)
print("Training started...")
for epoch in range(epochs):
    hidden = model.init_hidden(X.size(0))
    optimizer.zero_grad()
    output, hidden = model(X, hidden)
    loss = criterion(output.view(-1, vocab_size), Y.view(-1))
    loss.backward()
    optimizer.step()
    if (epoch+1) % 20 == 0:
        print(f"Epoch {epoch+1}, Loss: {loss.item():.4f}")
print("Training Completed")
def generate_text(start_text, length=20):
    model.eval()
    input_seq = torch.tensor([[char_to_idx[ch] for ch in start_text]])
    hidden = model.init_hidden(1)
    result = start_text
    for _ in range(length):
        output, hidden = model(input_seq, hidden)
        prob = torch.softmax(output[0, -1], dim=0)
        next_char_idx = torch.multinomial(prob, 1).item()
        next_char = idx_to_char[next_char_idx]
        result += next_char
        input_seq = torch.tensor([[next_char_idx]])

    return result
start = "hello"
print("\nGenerated Text:")
print(generate_text(start, 20))